#!/bin/bash

for f in *.cpp *.h 
do
	bcpp -fnc bcpp.cfg $f > ./bccpTemp~
	if [ $? -ne 127 ]
	then
		cp ./bccpTemp~ ./$f
	else
		echo "bcpp not installed.  Install and try, try again!"
		exit
	fi
done

rm ./bccpTemp~
